/* Здесь хранятся демонстрационные данные магазина и каталога. */
(function exposeData(root, factory) {
  const data = factory();
  if (typeof module === 'object' && module.exports) module.exports = data;
  root.FashionStoreData = data;
})(typeof globalThis !== 'undefined' ? globalThis : this, function createData() {
  const STORE = {
    name: 'Фэшн стор',
    tagline: 'Стильная женская одежда на каждый день',
    description: 'Спокойная база и выразительные детали для города, работы и отдыха.',
    address: 'Демонстрационный адрес: ул. Стильная, 12',
    hours: 'Ежедневно, 10:00–20:00',
    support: '@fashion_store_demo',
    phone: '+7 (900) 123-45-67',
  };

  const CATEGORIES = [
    { id: 'all', title: 'Все' },
    { id: 'dresses', title: 'Платья' },
    { id: 'jackets', title: 'Жакеты' },
    { id: 'trousers', title: 'Брюки' },
    { id: 'knitwear', title: 'Трикотаж' },
    { id: 'shirts', title: 'Рубашки' },
  ];

  const PRODUCTS = [
    {
      id: 'dress-air',
      name: 'Платье Воздух',
      category: 'dresses',
      price: 5990,
      oldPrice: null,
      badge: 'Новинка',
      images: ['assets/dress-air.jpg'],
      colors: [
        { id: 'blue', name: 'Голубой', hex: '#9ec9e6' },
        { id: 'milk', name: 'Молочный', hex: '#eee9df' },
      ],
      description: 'Лёгкое платье длины миди с мягко очерченной талией и свободной юбкой.',
      composition: 'Вискоза 72%, полиэстер 25%, эластан 3%',
      care: 'Деликатная стирка при 30 °C, сушить на плечиках.',
      fit: 'Полуприлегающая посадка, размер в размер.',
      model: 'Рост модели 174 см, на модели размер S.',
      measurements: { XS: '84–64–90', S: '88–68–94', M: '92–72–98', L: '96–76–102' },
      variants: [
        { colorId: 'blue', size: 'S', stock: 3 },
        { colorId: 'blue', size: 'M', stock: 1 },
        { colorId: 'blue', size: 'L', stock: 0 },
        { colorId: 'milk', size: 'S', stock: 2 },
        { colorId: 'milk', size: 'M', stock: 2 },
        { colorId: 'milk', size: 'L', stock: 1 },
      ],
    },
    {
      id: 'dress-midi',
      name: 'Платье Миди',
      category: 'dresses',
      price: 7490,
      oldPrice: 8990,
      badge: null,
      images: ['assets/dress-midi.jpg'],
      colors: [
        { id: 'black', name: 'Чёрный', hex: '#242424' },
        { id: 'berry', name: 'Ягодный', hex: '#8a3d55' },
      ],
      description: 'Лаконичное платье на запах с поясом и аккуратным V-образным вырезом.',
      composition: 'Вискоза 65%, полиэстер 30%, эластан 5%',
      care: 'Ручная или деликатная стирка при 30 °C.',
      fit: 'Регулируется поясом, подходит для разной полноты груди.',
      model: 'Рост модели 171 см, на модели размер S.',
      measurements: { XS: '82–62–88', S: '86–66–92', M: '90–70–96', L: '94–74–100' },
      variants: [
        { colorId: 'black', size: 'XS', stock: 1 },
        { colorId: 'black', size: 'S', stock: 4 },
        { colorId: 'black', size: 'M', stock: 2 },
        { colorId: 'berry', size: 'S', stock: 1 },
        { colorId: 'berry', size: 'M', stock: 0 },
        { colorId: 'berry', size: 'L', stock: 2 },
      ],
    },
    {
      id: 'jacket-soft',
      name: 'Жакет Софт',
      category: 'jackets',
      price: 9990,
      oldPrice: null,
      badge: 'Последний',
      images: ['assets/jacket-soft.jpg'],
      colors: [{ id: 'sand', name: 'Песочный', hex: '#c9ad8a' }],
      description: 'Мягкий однобортный жакет с деликатной линией плеча и двумя карманами.',
      composition: 'Вискоза 48%, полиэстер 47%, эластан 5%',
      care: 'Только профессиональная химчистка.',
      fit: 'Свободная посадка; для более собранного силуэта выбирайте размер меньше.',
      model: 'Рост модели 176 см, на модели размер M.',
      measurements: { S: '88–68–94', M: '92–72–98', L: '96–76–102' },
      variants: [
        { colorId: 'sand', size: 'S', stock: 0 },
        { colorId: 'sand', size: 'M', stock: 1 },
        { colorId: 'sand', size: 'L', stock: 0 },
      ],
    },
    {
      id: 'jacket-city',
      name: 'Жакет Сити',
      category: 'jackets',
      price: 11990,
      oldPrice: null,
      badge: 'Новинка',
      images: ['assets/jacket-city.jpg'],
      colors: [
        { id: 'graphite', name: 'Графит', hex: '#555861' },
        { id: 'milk', name: 'Молочный', hex: '#eee9df' },
      ],
      description: 'Структурный двубортный жакет для офиса и расслабленных образов с джинсами.',
      composition: 'Шерсть 22%, вискоза 38%, полиэстер 40%',
      care: 'Профессиональная химчистка, хранить на широких плечиках.',
      fit: 'Прямой силуэт с умеренным объёмом в плечах.',
      model: 'Рост модели 178 см, на модели размер S.',
      measurements: { S: '88–68–94', M: '92–72–98', L: '96–76–102' },
      variants: [
        { colorId: 'graphite', size: 'S', stock: 2 },
        { colorId: 'graphite', size: 'M', stock: 2 },
        { colorId: 'graphite', size: 'L', stock: 1 },
        { colorId: 'milk', size: 'S', stock: 1 },
        { colorId: 'milk', size: 'M', stock: 0 },
        { colorId: 'milk', size: 'L', stock: 1 },
      ],
    },
    {
      id: 'trousers-wide',
      name: 'Брюки Палаццо',
      category: 'trousers',
      price: 6490,
      oldPrice: null,
      badge: null,
      images: ['assets/trousers-wide.jpg'],
      colors: [
        { id: 'black', name: 'Чёрный', hex: '#242424' },
        { id: 'beige', name: 'Бежевый', hex: '#d2bea3' },
      ],
      description: 'Широкие брюки с высокой посадкой, стрелками и мягким движением ткани.',
      composition: 'Полиэстер 62%, вискоза 33%, эластан 5%',
      care: 'Деликатная стирка при 30 °C, гладить с изнанки.',
      fit: 'Высокая посадка, свободные по бедру.',
      model: 'Рост модели 175 см, на модели размер S.',
      measurements: { S: '68–94, длина 108', M: '72–98, длина 109', L: '76–102, длина 110' },
      variants: [
        { colorId: 'black', size: 'S', stock: 3 },
        { colorId: 'black', size: 'M', stock: 3 },
        { colorId: 'black', size: 'L', stock: 1 },
        { colorId: 'beige', size: 'S', stock: 2 },
        { colorId: 'beige', size: 'M', stock: 0 },
        { colorId: 'beige', size: 'L', stock: 2 },
      ],
    },
    {
      id: 'knit-cardigan',
      name: 'Кардиган Облако',
      category: 'knitwear',
      price: 5490,
      oldPrice: 6490,
      badge: null,
      images: ['assets/knit-cardigan.jpg'],
      colors: [
        { id: 'milk', name: 'Молочный', hex: '#eee9df' },
        { id: 'sky', name: 'Небесный', hex: '#b5d8eb' },
      ],
      description: 'Мягкий кардиган свободного кроя с аккуратными пуговицами в тон.',
      composition: 'Хлопок 50%, акрил 30%, шерсть 20%',
      care: 'Ручная стирка, сушить горизонтально.',
      fit: 'Свободный силуэт, можно носить вторым слоем.',
      model: 'Рост модели 170 см, на модели размер S.',
      measurements: { S: 'ширина 52, длина 59', M: 'ширина 56, длина 61' },
      variants: [
        { colorId: 'milk', size: 'S', stock: 5 },
        { colorId: 'milk', size: 'M', stock: 3 },
        { colorId: 'sky', size: 'S', stock: 1 },
        { colorId: 'sky', size: 'M', stock: 2 },
      ],
    },
    {
      id: 'knit-top',
      name: 'Топ Риб',
      category: 'knitwear',
      price: 3490,
      oldPrice: null,
      badge: 'Новинка',
      images: ['assets/knit-top.jpg'],
      colors: [
        { id: 'white', name: 'Белый', hex: '#f7f7f5' },
        { id: 'cocoa', name: 'Какао', hex: '#8d6e60' },
      ],
      description: 'Базовый трикотажный топ с плотной фактурой и мягким квадратным вырезом.',
      composition: 'Хлопок 75%, вискоза 20%, эластан 5%',
      care: 'Деликатная стирка при 30 °C.',
      fit: 'По фигуре, эластичная ткань.',
      model: 'Рост модели 173 см, на модели размер S.',
      measurements: { XS: '82–62–88', S: '86–66–92', M: '90–70–96' },
      variants: [
        { colorId: 'white', size: 'XS', stock: 4 },
        { colorId: 'white', size: 'S', stock: 4 },
        { colorId: 'white', size: 'M', stock: 2 },
        { colorId: 'cocoa', size: 'XS', stock: 0 },
        { colorId: 'cocoa', size: 'S', stock: 2 },
        { colorId: 'cocoa', size: 'M', stock: 2 },
      ],
    },
    {
      id: 'shirt-relaxed',
      name: 'Рубашка Релакс',
      category: 'shirts',
      price: 4990,
      oldPrice: null,
      badge: null,
      images: ['assets/shirt-relaxed.jpg'],
      colors: [
        { id: 'white', name: 'Белый', hex: '#f7f7f5' },
        { id: 'blue', name: 'Голубой', hex: '#9ec9e6' },
      ],
      description: 'Свободная рубашка из плотного хлопка с удлинённой спинкой.',
      composition: 'Хлопок 97%, эластан 3%',
      care: 'Стирка при 30 °C, отпаривание на средней температуре.',
      fit: 'Oversize; для более компактной посадки выбирайте размер меньше.',
      model: 'Рост модели 177 см, на модели размер M.',
      measurements: { S: 'ширина 55, длина 72', M: 'ширина 59, длина 74', L: 'ширина 63, длина 76' },
      variants: [
        { colorId: 'white', size: 'S', stock: 3 },
        { colorId: 'white', size: 'M', stock: 1 },
        { colorId: 'white', size: 'L', stock: 1 },
        { colorId: 'blue', size: 'S', stock: 0 },
        { colorId: 'blue', size: 'M', stock: 2 },
        { colorId: 'blue', size: 'L', stock: 2 },
      ],
    },
  ];

  const DELIVERY_METHODS = [
    {
      id: 'pickup',
      title: 'Самовывоз',
      description: 'Демонстрационная точка магазина, готовность обычно в течение дня.',
      price: 0,
      demo: true,
    },
    {
      id: 'courier',
      title: 'Курьер по городу',
      description: 'Демонстрационная доставка в пределах города.',
      price: 490,
      demo: true,
    },
  ];

  return { STORE, CATEGORIES, PRODUCTS, DELIVERY_METHODS };
});
